In [31]:
import pandas as pd
import os
from sqlalchemy import create_engine
import warnings
warnings.filterwarnings('ignore')

In [9]:
engine = create_engine('mysql+pymysql://root:yogesh08@localhost:3306/e_commerce')

In [10]:
files_to_load = {
    'olist_orders_dataset.csv': 'orders',
    'olist_sellers_dataset.csv': 'sellers',
    'olist_order_items_dataset.csv': 'order_items',
    'olist_order_reviews_dataset.csv': 'order_reviews'
}

In [11]:
for file_name, table_name in files_to_load.items():
    print(f"Loading {file_name} into MySQL table '{table_name}'...")
    
    df = pd.read_csv(file_name)

    df.to_sql(name=table_name, con=engine, if_exists='replace', index=False, chunksize=10000)
    
    print(f"Successfully loaded {len(df)} rows into '{table_name}'.")

print("\nAll datasets have been successfully loaded into MySQL!")

Loading olist_orders_dataset.csv into MySQL table 'orders'...
Successfully loaded 99441 rows into 'orders'.
Loading olist_sellers_dataset.csv into MySQL table 'sellers'...
Successfully loaded 3095 rows into 'sellers'.
Loading olist_order_items_dataset.csv into MySQL table 'order_items'...
Successfully loaded 112650 rows into 'order_items'.
Loading olist_order_reviews_dataset.csv into MySQL table 'order_reviews'...
Successfully loaded 99224 rows into 'order_reviews'.

All datasets have been successfully loaded into MySQL!

In [12]:
query = """
WITH VendorMetrics AS (
    SELECT 
        s.seller_id,
        COUNT(DISTINCT o.order_id) AS Total_Orders,
        
        AVG(DATEDIFF(o.order_delivered_customer_date, o.order_estimated_delivery_date)) AS Avg_Shipping_Delay_Days,
        
        SUM(CASE WHEN o.order_status = 'canceled' THEN 1 ELSE 0 END) / COUNT(DISTINCT o.order_id) * 100 AS Cancellation_Rate,
        
        SUM(CASE WHEN orv.review_score = 1 THEN 1 ELSE 0 END) / COUNT(DISTINCT o.order_id) * 100 AS Dispute_Frequency
        
    FROM sellers AS s
    JOIN order_items AS oi ON s.seller_id = oi.seller_id
    JOIN orders AS o ON oi.order_id = o.order_id
    LEFT JOIN order_reviews AS orv ON o.order_id = orv.order_id 
    
    GROUP BY s.seller_id
    HAVING Total_Orders > 10 
)


SELECT 
    seller_id,
    Total_Orders,
    ROUND(Avg_Shipping_Delay_Days, 2) AS Avg_Shipping_Delay,
    ROUND(Cancellation_Rate, 2) AS Cancellation_Rate,
    ROUND(Dispute_Frequency, 2) AS Dispute_Frequency,
    
    CASE 
        WHEN Dispute_Frequency >= 15 AND Avg_Shipping_Delay_Days > 3 THEN 'Unreliable'
        WHEN Cancellation_Rate > 10 THEN 'Unreliable'
        WHEN Dispute_Frequency >= 10 OR Avg_Shipping_Delay_Days > 0 THEN 'At-Risk'
        ELSE 'Reliable'
    END AS Target_Label
    
FROM VendorMetrics
ORDER BY Total_Orders DESC;

"""

In [13]:
df = pd.read_sql(query,engine)

In [14]:
df

,seller_id,Total_Orders,Avg_Shipping_Delay,Cancellation_Rate,Dispute_Frequency,Target_Label
0,6560211a19b47992c3666cc44a7e94c0,1854,-11.72,0.43,14.40,At-Risk
1,4a3ca9315b744ce9f8e9374361493884,1806,-9.66,0.11,16.28,At-Risk
2,cc419e0650a3c5ba77189a1882b7556a,1706,-13.03,0.53,12.60,At-Risk
3,1f50f920176fa81dab994f9023523100,1404,-10.83,0.07,20.09,At-Risk
4,da8622b14eb17ae2831f4ac5b9dab84a,1314,-11.31,0.00,13.47,At-Risk
...,...,...,...,...,...,...
1196,f08a5b9dd6767129688d001acafc21e5,11,-8.44,0.00,54.55,At-Risk
1197,f0e103c63864d5405b958d984b6e94c9,11,-12.00,0.00,0.00,Reliable
1198,fa74b2f3287d296e9fbd2cc80f2d1cf1,11,-5.60,0.00,63.64,At-Risk
1199,fe701d88b67eaca109dffd464d1be9f9,11,-15.90,0.00,18.18,At-Risk
1200,ff4e2d38692ce827b1a4f4b8196e680d,11,-14.09,0.00,0.00,Reliable

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1201 entries, 0 to 1200
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   seller_id           1201 non-null   object
 1   Total_Orders        1201 non-null   int64
 2   Avg_Shipping_Delay  1201 non-null   float64
 3   Cancellation_Rate   1201 non-null   float64
 4   Dispute_Frequency   1201 non-null   float64
 5   Target_Label        1201 non-null   object
dtypes: float64(3), int64(1), object(2)
memory usage: 56.4+ KB

In [16]:
df.isnull().sum()

seller_id             0
Total_Orders          0
Avg_Shipping_Delay    0
Cancellation_Rate     0
Dispute_Frequency     0
Target_Label          0
dtype: int64

In [17]:
df['Target_Label'].value_counts()

Target_Label
At-Risk       653
Reliable      535
Unreliable     13
Name: count, dtype: int64

In [18]:
label_mapping = {'Reliable':0, 'At-Risk':1, 'Unreliable':2}
df['Target_Label'] = df['Target_Label'].map(label_mapping)

In [21]:
df.head()

,seller_id,Total_Orders,Avg_Shipping_Delay,Cancellation_Rate,Dispute_Frequency,Target_Label
0,6560211a19b47992c3666cc44a7e94c0,1854,-11.72,0.43,14.40,1
1,4a3ca9315b744ce9f8e9374361493884,1806,-9.66,0.11,16.28,1
2,cc419e0650a3c5ba77189a1882b7556a,1706,-13.03,0.53,12.60,1
3,1f50f920176fa81dab994f9023523100,1404,-10.83,0.07,20.09,1
4,da8622b14eb17ae2831f4ac5b9dab84a,1314,-11.31,0.00,13.47,1

In [22]:
X = df.drop(columns = ['seller_id','Target_Label'])
y = df['Target_Label']

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [74]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [75]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled,y_train)

LogisticRegression()

In [76]:
y_pred = model.predict(X_test_scaled)
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       2, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1])

In [77]:
accuracy_score(y_test,y_pred)

0.975103734439834

In [78]:
confusion_matrix(y_test,y_pred)

array([[103,   0,   0],
       [  5, 130,   0],
       [  0,   1,   2]])

In [79]:
from sklearn.ensemble import RandomForestClassifier

In [80]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42
)

In [81]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [82]:
y_pred_rf = rf_model.predict(X_test)

In [83]:
accuracy = accuracy_score(y_test,y_pred_rf)

In [84]:
accuracy

0.995850622406639

In [85]:
confusion_matrix(y_test,y_pred_rf)

array([[103,   0,   0],
       [  0, 135,   0],
       [  0,   1,   2]])

In [86]:
from xgboost import XGBClassifier

In [87]:
xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1,max_depth=3,
                          eval_metric='mlogloss',random_state=42)

In [88]:
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [89]:
y_pred_xgb = xgb_model.predict(X_test)

In [90]:
accuracy = accuracy_score(y_test,y_pred_xgb)

In [91]:
accuracy

0.995850622406639

In [92]:
confusion_matrix(y_test,y_pred_xgb)

array([[103,   0,   0],
       [  0, 135,   0],
       [  0,   1,   2]])

In [93]:
import joblib

In [94]:
joblib.dump(scaler, 'standard_scaler.pkl')

['standard_scaler.pkl']

In [95]:
joblib.dump(model, 'logistic_model.pkl')
joblib.dump(rf_model, 'random_forest_model.pkl')
joblib.dump(xgb_model, 'xgboost_model.pkl')

['xgboost_model.pkl']